global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook'

receivers:
  - name: 'jenkins-rollback-webhook'
    webhook_configs:
      - url: 'http://172.17.0.1:8080/generic-webhook-trigger/invoke?token=ROLLBACK_934365_TOKEN'
        send_resolved: false
