apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
spec:
  type: NodePort
  selector:
    app: sentiment-api
    slot: blue
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32500

